### ISSUE TITLE
Very clean

### ISSUE THREAD

**Issue by mo-shawa** [AlexNelson52/Odin-FormValidation#1]
Excellent work

**Comment by AlexNelson52** [comment]
Wtf is this
    On Sunday, April 21, 2024 at 10:09:31 AM EDT, Mahmoud Shawa ***@***.***> wrote:  
 
 


Excellent work

**Comment by mo-shawa** [comment]
Kindly refer to the below function:

https://github.com/AlexNelson52/Odin-FormValidation/blob/39c886ca252e736ea7f629a65f8e1b821ebf0a99/src/passwordValidate.js#L1-L6

This works, however there is a redundancy in your function - let me explain!

We often check whether an expression (e.g. `passConf === pass` ) is true, in order to do something else based on the result.
In your case, which is a common one, you intend to return `true` or `false` depending on whether or not the expression evaluates to `true` or `false`. 

This means that we can simply return the expression, since it *inherently* will resolve to either `true` or `false`

Example:

```js
 export default function (pass, passConf) { 
  return passConf === pass
 } 
```

Or as an arrow function: 

```js
const validatePass = (pass, passConf) => passConf === pass

export default validatePass
```
 
I hope this was of use and assistance! Kindly reply to this issue if there's anything I can expound upon. :)

**Comment by AlexNelson52** [comment]
wow, thank you sir. Sometimes my brain just doesn't want to logically think.

**Comment by mo-shawa** [comment]
No problem jackass!
